name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.0

  # Plugins for parsing css
  csslib: ^0.17.1
  css_colors: ^1.1.1

  # Plugins for rendering the <video> tag.
  video_player: ^2.4.2
  chewie: ^1.3.3

  # Plugin for rendering the <iframe> tag. 
  webview_media:
    git:
      url: https://github.com/skore-io/webview_media
      ref: update/migrate_to_nullsafety

  # Plugins for rendering the <audio> tag.
  chewie_audio: ^1.3.0

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^1.1.0

  # http for verifications of links
  http:

  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

